CREATE TABLE IF NOT EXISTS team_people (
  id TEXT PRIMARY KEY CHECK (id ~ '^[a-zA-Z0-9-]{1,100}$'),
  name TEXT NOT NULL CHECK (char_length(name) BETWEEN 1 AND 160),
  initials TEXT NOT NULL CHECK (char_length(initials) BETWEEN 1 AND 8),
  publication_consent_at TIMESTAMPTZ,
  publication_consent_by TEXT,
  version INTEGER NOT NULL DEFAULT 1 CHECK (version >= 1),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by TEXT NOT NULL CHECK (char_length(created_by) BETWEEN 1 AND 320),
  updated_by TEXT NOT NULL CHECK (char_length(updated_by) BETWEEN 1 AND 320),
  CONSTRAINT team_people_consent_pair CHECK (
    (publication_consent_at IS NULL AND publication_consent_by IS NULL)
    OR (publication_consent_at IS NOT NULL AND char_length(publication_consent_by) BETWEEN 1 AND 320)
  ),
  CONSTRAINT team_people_timestamp_order CHECK (updated_at >= created_at)
);

CREATE TABLE IF NOT EXISTS team_profiles (
  id TEXT PRIMARY KEY CHECK (id ~ '^[a-zA-Z0-9-]{1,100}$'),
  person_id TEXT NOT NULL REFERENCES team_people(id) ON DELETE CASCADE,
  section TEXT NOT NULL CHECK (section IN ('leader', 'tutor')),
  status TEXT NOT NULL CHECK (status IN ('draft', 'published')),
  sort_order INTEGER NOT NULL CHECK (sort_order BETWEEN 0 AND 1000000),
  school TEXT NOT NULL DEFAULT '' CHECK (char_length(school) <= 300),
  grade TEXT NOT NULL DEFAULT '' CHECK (char_length(grade) <= 40),
  show_school BOOLEAN NOT NULL DEFAULT FALSE,
  show_grade BOOLEAN NOT NULL DEFAULT FALSE,
  role_en TEXT NOT NULL DEFAULT '' CHECK (char_length(role_en) <= 500),
  role_zh_hant TEXT NOT NULL DEFAULT '' CHECK (char_length(role_zh_hant) <= 500),
  role_zh_hans TEXT NOT NULL DEFAULT '' CHECK (char_length(role_zh_hans) <= 500),
  school_display_en TEXT NOT NULL DEFAULT '' CHECK (char_length(school_display_en) <= 300),
  school_display_zh_hant TEXT NOT NULL DEFAULT '' CHECK (char_length(school_display_zh_hant) <= 300),
  school_display_zh_hans TEXT NOT NULL DEFAULT '' CHECK (char_length(school_display_zh_hans) <= 300),
  languages_en TEXT NOT NULL DEFAULT '' CHECK (char_length(languages_en) <= 500),
  languages_zh_hant TEXT NOT NULL DEFAULT '' CHECK (char_length(languages_zh_hant) <= 500),
  languages_zh_hans TEXT NOT NULL DEFAULT '' CHECK (char_length(languages_zh_hans) <= 500),
  strengths_en TEXT NOT NULL DEFAULT '' CHECK (char_length(strengths_en) <= 1000),
  strengths_zh_hant TEXT NOT NULL DEFAULT '' CHECK (char_length(strengths_zh_hant) <= 1000),
  strengths_zh_hans TEXT NOT NULL DEFAULT '' CHECK (char_length(strengths_zh_hans) <= 1000),
  summary_en TEXT NOT NULL DEFAULT '' CHECK (char_length(summary_en) <= 2000),
  summary_zh_hant TEXT NOT NULL DEFAULT '' CHECK (char_length(summary_zh_hant) <= 2000),
  summary_zh_hans TEXT NOT NULL DEFAULT '' CHECK (char_length(summary_zh_hans) <= 2000),
  bio_en TEXT NOT NULL DEFAULT '' CHECK (char_length(bio_en) <= 5000),
  bio_zh_hant TEXT NOT NULL DEFAULT '' CHECK (char_length(bio_zh_hant) <= 5000),
  bio_zh_hans TEXT NOT NULL DEFAULT '' CHECK (char_length(bio_zh_hans) <= 5000),
  hobbies_en TEXT NOT NULL DEFAULT '' CHECK (char_length(hobbies_en) <= 2000),
  hobbies_zh_hant TEXT NOT NULL DEFAULT '' CHECK (char_length(hobbies_zh_hant) <= 2000),
  hobbies_zh_hans TEXT NOT NULL DEFAULT '' CHECK (char_length(hobbies_zh_hans) <= 2000),
  version INTEGER NOT NULL DEFAULT 1 CHECK (version >= 1),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by TEXT NOT NULL CHECK (char_length(created_by) BETWEEN 1 AND 320),
  updated_by TEXT NOT NULL CHECK (char_length(updated_by) BETWEEN 1 AND 320),
  CONSTRAINT team_profiles_person_section_unique UNIQUE (person_id, section),
  CONSTRAINT team_profiles_public_visibility CHECK (
    (NOT show_school OR char_length(school) > 0)
    AND (NOT show_grade OR char_length(grade) > 0)
  ),
  CONSTRAINT team_profiles_published_english CHECK (
    status = 'draft'
    OR (
      char_length(role_en) > 0
      AND char_length(bio_en) > 0
      AND (section <> 'tutor' OR char_length(summary_en) > 0)
    )
  ),
  CONSTRAINT team_profiles_timestamp_order CHECK (updated_at >= created_at)
);

CREATE INDEX IF NOT EXISTS team_profiles_public_order_idx
  ON team_profiles (section, status, sort_order, id);
CREATE INDEX IF NOT EXISTS team_profiles_person_idx ON team_profiles (person_id);

CREATE OR REPLACE FUNCTION enforce_team_profile_publication_consent()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.status = 'published' AND NOT EXISTS (
    SELECT 1 FROM team_people
    WHERE id = NEW.person_id
      AND publication_consent_at IS NOT NULL
      AND publication_consent_by IS NOT NULL
  ) THEN
    RAISE EXCEPTION 'Publication consent is required'
      USING ERRCODE = '23514', CONSTRAINT = 'team_profiles_publication_consent';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS team_profiles_publication_consent_trigger ON team_profiles;
CREATE TRIGGER team_profiles_publication_consent_trigger
  BEFORE INSERT OR UPDATE OF status, person_id ON team_profiles
  FOR EACH ROW EXECUTE FUNCTION enforce_team_profile_publication_consent();

ALTER TABLE team_people ENABLE ROW LEVEL SECURITY;
ALTER TABLE team_profiles ENABLE ROW LEVEL SECURITY;

INSERT INTO team_people (
  id, name, initials, publication_consent_at, publication_consent_by, created_by, updated_by
) VALUES
  ('person-zoe-lu', 'Zoe Lu', 'ZL', '2026-07-31T00:00:00.000Z'::timestamptz, 'ihearprogram@gmail.com', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('person-howard-m-ren', 'Howard M. Ren', 'HR', '2026-07-31T00:00:00.000Z'::timestamptz, 'ihearprogram@gmail.com', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('person-daniel-hollis', 'Daniel Hollis', 'DH', '2026-07-31T00:00:00.000Z'::timestamptz, 'ihearprogram@gmail.com', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('person-amber-lin', 'Amber Lin', 'AL', '2026-07-31T00:00:00.000Z'::timestamptz, 'ihearprogram@gmail.com', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('person-andrea-lin', 'Andrea Lin', 'AL', '2026-07-31T00:00:00.000Z'::timestamptz, 'ihearprogram@gmail.com', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('person-basmeha-islam', 'Basmeha Islam', 'BI', '2026-07-31T00:00:00.000Z'::timestamptz, 'ihearprogram@gmail.com', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('person-bryan-wang', 'Bryan Wang', 'BW', '2026-07-31T00:00:00.000Z'::timestamptz, 'ihearprogram@gmail.com', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('person-cali-chan', 'Cali Chan', 'CC', '2026-07-31T00:00:00.000Z'::timestamptz, 'ihearprogram@gmail.com', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('person-camille-ganhao', 'Camille Ganhao', 'CG', '2026-07-31T00:00:00.000Z'::timestamptz, 'ihearprogram@gmail.com', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('person-cecilia-shao', 'Cecilia Shao', 'CS', '2026-07-31T00:00:00.000Z'::timestamptz, 'ihearprogram@gmail.com', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('person-charlene-chen', 'Charlene Chen', 'CC', '2026-07-31T00:00:00.000Z'::timestamptz, 'ihearprogram@gmail.com', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('person-charlie-sellar', 'Charlie Sellar', 'CS', '2026-07-31T00:00:00.000Z'::timestamptz, 'ihearprogram@gmail.com', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('person-danniel-wang', 'Danniel wang', 'DW', '2026-07-31T00:00:00.000Z'::timestamptz, 'ihearprogram@gmail.com', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('person-doris-tsai', 'Doris Tsai', 'DT', '2026-07-31T00:00:00.000Z'::timestamptz, 'ihearprogram@gmail.com', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('person-ella-wen', 'Ella Wen', 'EW', '2026-07-31T00:00:00.000Z'::timestamptz, 'ihearprogram@gmail.com', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('person-emily-ye', 'Emily Ye', 'EY', '2026-07-31T00:00:00.000Z'::timestamptz, 'ihearprogram@gmail.com', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('person-emma-ganhao', 'Emma Ganhao', 'EG', '2026-07-31T00:00:00.000Z'::timestamptz, 'ihearprogram@gmail.com', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('person-howard', 'Howard', 'H', '2026-07-31T00:00:00.000Z'::timestamptz, 'ihearprogram@gmail.com', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('person-jayden-yang', 'Jayden Yang', 'JY', '2026-07-31T00:00:00.000Z'::timestamptz, 'ihearprogram@gmail.com', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('person-jessie-chen', 'Jessie Chen', 'JC', '2026-07-31T00:00:00.000Z'::timestamptz, 'ihearprogram@gmail.com', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('person-karen-pan', 'Karen Pan', 'KP', '2026-07-31T00:00:00.000Z'::timestamptz, 'ihearprogram@gmail.com', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('person-lisa-xu', 'Lisa Xu', 'LX', '2026-07-31T00:00:00.000Z'::timestamptz, 'ihearprogram@gmail.com', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('person-marcus-ke', 'Marcus Ke', 'MK', '2026-07-31T00:00:00.000Z'::timestamptz, 'ihearprogram@gmail.com', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('person-olivia-wang', 'Olivia Wang', 'OW', '2026-07-31T00:00:00.000Z'::timestamptz, 'ihearprogram@gmail.com', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('person-ria-kumar', 'Ria Kumar', 'RK', '2026-07-31T00:00:00.000Z'::timestamptz, 'ihearprogram@gmail.com', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('person-tristan-echezarreta', 'Tristan Echezarreta', 'TE', '2026-07-31T00:00:00.000Z'::timestamptz, 'ihearprogram@gmail.com', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('person-winston-wu', 'Winston Wu', 'WW', '2026-07-31T00:00:00.000Z'::timestamptz, 'ihearprogram@gmail.com', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com')
ON CONFLICT (id) DO NOTHING;

INSERT INTO team_profiles (
  id, person_id, section, status, sort_order, school, grade, show_school, show_grade,
  role_en, role_zh_hant, role_zh_hans,
  school_display_en, school_display_zh_hant, school_display_zh_hans,
  languages_en, languages_zh_hant, languages_zh_hans,
  strengths_en, strengths_zh_hant, strengths_zh_hans,
  summary_en, summary_zh_hant, summary_zh_hans,
  bio_en, bio_zh_hant, bio_zh_hans,
  hobbies_en, hobbies_zh_hant, hobbies_zh_hans,
  created_by, updated_by
) VALUES
  ('leader-zoe-lu', 'person-zoe-lu', 'leader', 'published', 10, '', '', false, false, 'Founder & Co-President · Co-Director, Tutor Training & Curriculum · Lead Tutor', '創辦人暨共同會長 · 導師培訓與課程共同總監 · 首席導師', '创始人兼联合会长 · 导师培训与课程联合总监 · 首席导师', '', '', '', '', '', '', '', '', '', '', '', '', 'Zoe founded iHear to address communication barriers faced by students with hearing loss and other communication needs. As Founder and Co-President, she sets the organization''s vision, guides long-term strategy, and represents iHear in partnerships and community initiatives. She helps design instructional frameworks and training structures that prioritize confidence-building, accessibility, and real-world communication, and remains actively involved as a Lead Tutor.', 'Zoe 創辦 iHear，以解決聽力損失及其他溝通需求學生面臨的溝通障礙。作為創辦人暨共同會長，她確立組織願景、引領長期策略，並代表 iHear 參與合作與社區倡議。她協助設計以建立自信、無障礙與真實溝通為優先的教學框架與培訓架構，並持續以首席導師身分積極參與。', 'Zoe 创办 iHear，以解决听力损失及其他沟通需求学生面临的沟通障碍。作为创始人兼联合会长，她确立组织愿景、引领长期战略，并代表 iHear 参与合作与社区倡议。她协助设计以建立自信、无障碍与真实沟通为优先的教学框架与培训体系，并持续以首席导师身份积极参与。', '', '', '', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('leader-howard-m-ren', 'person-howard-m-ren', 'leader', 'published', 20, '', '', false, false, 'Co-President · Lead Tutor', '共同會長 · 首席導師', '联合会长 · 首席导师', '', '', '', '', '', '', '', '', '', '', '', '', 'As Co-President, Howard supports iHear''s strategic planning and organizational coordination, helping ensure that programs run smoothly and align with the organization''s mission. He works closely with fellow leaders to support execution, communication, and internal collaboration, and serves as a Lead Tutor, bringing hands-on instructional experience and a student-centered perspective to leadership decisions.', '作為共同會長，Howard 支持 iHear 的策略規劃與組織協調，確保各項計畫順利運作並符合組織使命。他與其他領導者密切合作，支持執行、溝通與內部協作，並以首席導師身分為領導決策帶來第一線教學經驗與以學生為中心的視角。', '作为联合会长，Howard 支持 iHear 的战略规划与组织协调，确保各项目顺利运作并符合组织使命。他与其他领导者密切合作，支持执行、沟通与内部协作，并以首席导师身份为领导决策带来一线教学经验与以学生为中心的视角。', '', '', '', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('leader-daniel-hollis', 'person-daniel-hollis', 'leader', 'published', 30, '', '', false, false, 'Co-Director, Tutor Training & Curriculum · Team Lead · Lead Tutor', '導師培訓與課程共同總監 · 組長 · 首席導師', '导师培训与课程联合总监 · 组长 · 首席导师', '', '', '', '', '', '', '', '', '', '', '', '', 'Daniel plays a central role in shaping iHear''s instructional quality and tutor development. As Co-Director of Tutor Training & Curriculum, he leads the design and implementation of tutor training, curriculum materials, and quality standards across the program. He also serves as a Team Lead, supporting coordination and mentoring within the tutor team, and models best practices through structured, relationship-driven instruction.', 'Daniel 在塑造 iHear 的教學品質與導師發展方面扮演核心角色。作為導師培訓與課程共同總監，他主導導師培訓、課程教材與品質標準的設計與實施。他同時擔任組長，支持導師團隊的協調與輔導，並透過結構化、重視關係的教學示範最佳實踐。', 'Daniel 在塑造 iHear 的教学质量与导师发展方面扮演核心角色。作为导师培训与课程联合总监，他主导导师培训、课程教材与质量标准的设计与实施。他同时担任组长，支持导师团队的协调与辅导，并通过结构化、重视关系的教学示范最佳实践。', '', '', '', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('tutor-amber-lin', 'person-amber-lin', 'tutor', 'published', 10, 'Dominican International School (Taipei)', '10', true, true, 'Team Lead', '', '', 'Dominican International School (Taipei)', '', '', 'English, Chinese (Mandarin), Spanish (learning)', '', '', 'Hearing Loss & Cochlear Implant Support, Confidence Building, Personalized & Meticulous Coaching', '', '', 'Amber supports learners with patient, individualized coaching—drawing on her own experience as a cochlear implant user to help students build confidence in communication.', '', '', 'Amber joined iHear because she wants to give students the same opportunities and support she received growing up as a cochlear implant user. She understands how meaningful it is to have someone who believes in your potential and helps you build confidence step by step. Her tutoring style is very patient and supportive, emphasizing clear communication and a comfortable pace so learners feel safe practicing and speaking.', '', '', 'Sports and rock climbing.', '', '', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('tutor-andrea-lin', 'person-andrea-lin', 'tutor', 'published', 20, 'Kang Chiao International School (Taipei)', '8', true, true, 'Lead Tutor', '', '', 'Kang Chiao International School (Taipei)', '', '', 'English, Chinese (Mandarin)', '', '', 'Confidence Building, Pronunciation & Phoneme Coaching, Personalized & Meticulous Coaching', '', '', 'Andrea is a patient and encouraging tutor who supports early elementary learners through clear, real-life explanations and visual examples. She enjoys helping students build confidence in speaking and pronunciation by making learning feel friendly, relatable, and engaging.', '', '', 'Andrea joined iHear to deepen her interest in linguistics while supporting young learners in building confidence with English communication. She works primarily with early elementary students, focusing on speaking, pronunciation, and vocabulary development through patient, step-by-step guidance. Her tutoring style is highly visual and example-driven. Andrea often uses familiar objects, daily-life scenarios, and concrete examples to clarify abstract ideas—helping students understand and remember new words more easily. She treats her tutees like friends or siblings, creating a warm, supportive environment where learners feel comfortable asking questions and expressing themselves.', '', '', 'Reading, listening to music, designing layouts such as junk journals and book covers, learning more about linguistics, and skiing.', '', '', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('tutor-basmeha-islam', 'person-basmeha-islam', 'tutor', 'published', 30, 'Montgomery Blair High School (Maryland)', '10', true, true, 'Lead Tutor', '', '', 'Montgomery Blair High School (Maryland)', '', '', 'English, Bangla', '', '', 'ESL (English as Second Language Support), Confidence Building, Conversation & Real-World Speaking', '', '', 'Basmeha supports ESL learners using structured, friendly coaching. As a second-language English speaker herself, she helps students feel confident using English in real-life situations.', '', '', 'Basmeha joined iHear because she enjoys helping learners feel confident speaking English in real-life situations. Since English is also her second language, she understands the challenge of speaking up and wanted to support others through the same journey. Her tutoring style is patient, friendly, and structured. She uses simple explanations, sentence starters, guided practice, and an adjustable pace so learners feel comfortable and successful. She focuses on practical speaking that students can use immediately in daily life.', '', '', 'Drawing and painting to reset, keeping a favorite playlist on repeat, exploring new places, and volunteering.', '', '', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('tutor-bryan-wang', 'person-bryan-wang', 'tutor', 'published', 40, 'Winston Churchill High School (Maryland)', '9', true, true, 'Lead Tutor', '', '', 'Winston Churchill High School (Maryland)', '', '', 'English, Chinese (Mandarin)', '', '', 'Hearing Loss & Cochlear Implant Support, Confidence Building, Beginner & Young Learners', '', '', 'Bryan supports learners who need extra patience and encouragement. Drawing from his own hearing challenges, he creates a positive, visual learning environment that helps students feel confident speaking.', '', '', 'Bryan joined iHear to help kids in need and because he understands how difficult communication can feel. He has experienced fluid buildup and hearing issues himself, which helps him empathize deeply with learners who feel frustrated or discouraged. His tutoring style is patient, visual, and positivity-driven. Bryan praises students when they succeed, checks in frequently, and makes sure learners have time to ask questions at the end of each section. He aims to make each session encouraging so students can build confidence through small breakthroughs.', '', '', 'Origami, drawing, bird watching, and piano.', '', '', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('tutor-cali-chan', 'person-cali-chan', 'tutor', 'published', 50, 'Thomas S. Wootton HS', '9', true, true, 'Lead Tutor', '', '', 'Thomas S. Wootton HS', '', '', 'English, Chinese (Mandarin)', '', '', 'Beginner & Young Learners · Pronunciation & Phoneme Coaching · Structured & Step-by-Step Teaching', '', '', 'Cali is a patient, visual, and step-by-step tutor who helps learners build confident English communication through clear examples and lots of practice.', '', '', 'Cali joined iHear because she believes learning should feel fun, engaging, and accessible to everyone. In sessions, she blends patience, visuals, and repetition to help students truly understand what they are learning—especially when they are building foundational skills in pronunciation and vocabulary. Cali is also highly adaptive: she adjusts her pacing and explanations based on each learner needs, and she focuses on steady progress toward personal milestones so students feel encouraged, capable, and proud of their growth.', '', '', 'Rhythmic gymnastics, drawing, traveling — and she can juggle!.', '', '', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('tutor-camille-ganhao', 'person-camille-ganhao', 'tutor', 'published', 60, '', '', false, false, 'Lead Tutor', '', '', '', '', '', '', '', '', '', '', '', 'Camille helps young learners stay engaged through visual, goal-oriented lessons. She adapts her teaching style to each child''s learning needs with patience and creativity.', '', '', 'Camille joined iHear to help students learn English—especially learners who may not have the privilege of consistent schooling or who struggle to stay engaged in traditional classroom settings. She''s motivated by impact: helping learners build skills that can create future opportunities. Her tutoring style is highly visual, structured, and patient. Camille often uses imagery because it supports attention and comprehension—students can ’see what they''re talking about,’ which makes speaking and vocabulary more memorable. She also sets small goals at the beginning of lessons so sessions feel organized and learners know exactly what success looks like. Camille adapts to each learner''s style and believes patience is the key to steady progress, especially for younger students building foundations. Best at helping: Younger learners who benefit from visuals, clear goals, and patient support—especially students building confidence and early-stage English communication skills.', '', '', 'Camille plays football (soccer) and volleyball, enjoys guitar, and likes spending time with friends—high-energy interests that match her engaging tutoring approach.', '', '', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('tutor-cecilia-shao', 'person-cecilia-shao', 'tutor', 'published', 70, 'Saint James School (Maryland)', '9', true, true, 'Lead Tutor', '', '', 'Saint James School (Maryland)', '', '', 'English, Chinese (Mandarin)', '', '', 'Beginner & Young Learners, Confidence Building, Conversation & Real-World Speaking', '', '', 'Cecilia brings expressive, energetic tutoring to young learners. Using storytelling and performance-based activities, she helps students build focus and confidence.', '', '', 'Cecilia joined iHear because she finds it meaningful—and genuinely fun—to work with children. She has loved teaching since she was young (she even used to ’pretend-teach’ her siblings), and that early passion grew into a real interest in tutoring and helping learners build confidence. Her tutoring style is expressive and theatrical. Cecilia uses energetic storytelling, gestures, and performance-based learning to keep younger learners engaged—especially students who struggle to focus or feel nervous speaking. She creates an outgoing, supportive atmosphere where students feel safe to participate and gradually become more confident. Cecilia combines warmth with strong academics and discipline. She brings structure to lessons while keeping the energy high, helping learners stay motivated and present. Best at helping: Young learners who need confidence and engagement support—especially students who struggle with focus, shyness, or speaking hesitation.', '', '', 'Cecilia plays volleyball, softball, and violin, and she loves theater. She also shared she''s taking AP Calc AB and Advanced Chemistry—a sign of her strong work ethic and drive.', '', '', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('tutor-charlene-chen', 'person-charlene-chen', 'tutor', 'published', 80, '', '', false, false, 'Lead Tutor', '', '', '', '', '', '', '', '', '', '', '', 'Charlene creates personalized learning materials and teaches practical daily communication—especially supporting Mandarin-speaking learners with pronunciation and conversational confidence.', '', '', 'Charlene joined iHear because she''s passionate about helping students build confidence in English and believes her ability to tailor lessons can make a meaningful difference. She focuses on practical, real-life communication and helps learners strengthen pronunciation and conversational flow. What makes Charlene unique is her personalized approach: she creates learning materials based on each student''s needs instead of relying on a one-size-fits-all textbook. As a native Mandarin speaker, she understands common challenges Mandarin-speaking learners face and provides targeted, supportive coaching. Beyond tutoring, Charlene contributes to iHear as a community outreach speaker.', '', '', 'Playing piano and enjoying music; documentaries and reading.', '', '', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('tutor-charlie-sellar', 'person-charlie-sellar', 'tutor', 'published', 90, '', '', false, false, 'Lead Tutor', '', '', '', '', '', '', '', '', '', '', '', 'Charlie supports older learners (high school & college) who want to refine their English—especially pronunciation and speaking skills. He teaches with a ''quality over quantity'' approach, prioritizing deep understanding and personalized, engaging sessions.', '', '', 'Charlie joined iHear expecting that connecting with Taiwanese students as an English-only speaker would be difficult—but he found tutoring to be surprisingly rewarding and eye-opening. Through sessions, he''s gained new perspective, and he enjoys giving students the targeted practice they need to grow long-term. Charlie''s tutoring style is detail-focused and intentionally paced. Rather than rushing through slides, he slows down and emphasizes mastery, believing that if a student truly understands what they learned, the session is a success. He values quality over quantity, and he adjusts explanations and practice until concepts ''stick.'' What makes Charlie unique is how much he cares about making tutoring feel safe, fun, and human. He believes students shouldn''t feel like they''re sitting through a lecture—so he personalizes lessons to the learner''s interests and goals whenever possible. This approach makes learning more enjoyable, and often more productive.', '', '', 'Charlie is a classically trained pianist (10 years) and oboist (almost 5 years), and he hopes to major in music composition for film, TV, or video games. He''s also on a competitive rock climbing team and loves climbing whenever he can.', '', '', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('tutor-daniel-hollis', 'person-daniel-hollis', 'tutor', 'published', 100, 'Montgomery Blair High School (Maryland)', '10', true, true, 'Team Lead', '', '', 'Montgomery Blair High School (Maryland)', '', '', 'English', '', '', 'Conversation & Real-World Speaking, ESL (English as Second Language Support), Advanced & High-School Learners', '', '', 'Daniel helps students strengthen real-world communication while also supporting tutor growth. His sessions are conversational, structured, and confidence-focused.', '', '', 'Daniel joined iHear to make a meaningful impact on students learning English while also helping fellow tutors grow. He believes that confidence and consistency are key to effective communication and brings this philosophy into both his tutoring and leadership roles. Daniel''s tutoring sessions are structured but highly conversational. He typically begins with a warm check-in to build rapport, followed by focused lesson work using clear objectives and guided practice. He emphasizes patience, gives students time to organize their thoughts, and ends sessions with a recap to reinforce learning and retention. His approach helps students feel supported while still making steady progress toward fluency. Beyond tutoring, Daniel serves as Co-Director of Tutor Training & Curriculum, where he helps design training sessions, onboarding materials, and instructional frameworks that support tutors across iHear. He is particularly focused on helping tutors translate theory into practical, confidence-building teaching strategies. Despite his leadership role, Daniel remains closely involved in tutoring to ensure training stays grounded in real student needs.', '', '', 'Working out, playing cello, skateboarding, K-pop, cars, technology, and meeting new people.', '', '', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('tutor-danniel-wang', 'person-danniel-wang', 'tutor', 'published', 110, '', '', false, false, 'Lead Tutor', '', '', '', '', '', '', '', '', '', '', '', 'Danniel helps students build confidence in speaking through patient, step-by-step explanations and steady encouragement.', '', '', 'Danniel joined iHear because he enjoys helping people build confidence and practice real conversations. He teaches patiently and breaks learning into small steps so students can absorb material without feeling rushed. His calm approach supports learners who need a clear, supportive pace—especially when they are building foundational speaking skills.', '', '', 'Volleyball and table tennis.', '', '', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('tutor-doris-tsai', 'person-doris-tsai', 'tutor', 'published', 120, 'Dominican International School (Taipei)', '10', true, true, 'Lead Tutor', '', '', 'Dominican International School (Taipei)', '', '', 'English, Chinese (Mandarin)', '', '', 'ESL (English as Second Language Support), Hearing Loss & Cochlear Implant Support, Pronunciation & Phoneme Coaching', '', '', 'Doris supports learners through patient, structured lessons focused on pronunciation and engagement. She brings consistency and care to weekly tutoring sessions.', '', '', 'Doris joined iHear through a friend''s referral and contributes through consistent, patient tutoring. Her teaching style is structured and steady, helping learners practice English in a clear and organized way. Doris focuses on engagement and pronunciation practice—supporting learners who want to build skills by actively participating and staying curious during lessons. She has also contributed through weekly tutoring and shared that she has gained insights into different teaching approaches through iHear, showing strong reflection and growth as an instructor. Best at helping: Learners who enjoy active participation and want steady support in pronunciation, vocabulary development, and structured communication practice—especially students with hearing loss needs.', '', '', 'Doris enjoys swimming and free diving, and she also likes drawing.', '', '', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('tutor-ella-wen', 'person-ella-wen', 'tutor', 'published', 130, 'Winston Churchill High School (Maryland)', '10', true, true, 'Lead Tutor', '', '', 'Winston Churchill High School (Maryland)', '', '', 'English, Chinese (Mandarin)', '', '', 'Hearing Loss & Cochlear Implant Support, Confidence Building, Structured & Step-by-Step Teaching', '', '', 'Ella supports learners with hearing differences and beginner English learners through slow, clear, step-by-step instruction that builds confidence.', '', '', 'Ella joined iHear because she cares deeply about communication accessibility. She wants learners with hearing differences to feel confident not only in class, but also in everyday life. Her tutoring style is patient, structured, and step-by-step. Ella uses clear explanations and visual notes, breaking information into small parts and checking for understanding along the way. She is especially strong at supporting learners who need a slower pace and a welcoming environment where they can ask questions freely. Beyond tutoring, Ella contributes to iHear as a community outreach speaker.', '', '', 'Dancing, traveling, drawing, and watching anime.', '', '', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('tutor-emily-ye', 'person-emily-ye', 'tutor', 'published', 140, 'Montgomery Blair High School (Maryland)', '10', true, true, 'Team Lead', '', '', 'Montgomery Blair High School (Maryland)', '', '', 'English, Chinese (Mandarin)', '', '', 'Bilingual Support (English + Chinese), Structured & Step-by-Step Teaching, ESL (English as Second Language Support)', '', '', 'Emily supports learners with clear, patient teaching and uses bilingual (English + Chinese) explanations to help students understand more thoroughly.', '', '', 'Emily enjoys teaching and helping others learn new things. She tutors mostly in English, and when helpful, she uses Chinese to ensure students fully understand instructions, vocabulary, and concepts—especially when students need extra clarity. Her sessions prioritize clear explanation and steady pacing so learners can feel comfortable asking questions and practicing without pressure.', '', '', 'Painting, drawing, and creative art.', '', '', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('tutor-emma-ganhao', 'person-emma-ganhao', 'tutor', 'published', 150, 'Metropolitan International School (Panama City)', '10', true, true, 'Lead Tutor', '', '', 'Metropolitan International School (Panama City)', '', '', 'English', '', '', 'ESL (English as Second Language Support), Conversation & Real-World Speaking, Confidence Building', '', '', 'Emma builds strong tutor–student relationships through patient, conversation-driven lessons. She focuses on trust, encouragement, and helping learners feel excited about using English.', '', '', 'Emma joined iHear because she''s passionate about teaching languages to students who may not have access to strong support in school—or who simply need more practice and encouragement. As someone who speaks multiple languages fluently, she values bilingualism and believes communication skills can open real doors for a learner''s future. Her tutoring style is patient, informational, and conversation-driven. Emma builds sessions around trust and connection: she checks in, asks personal questions, and turns each lesson into a comfortable space for natural conversation. She also uses visual cues—like images and prompts—to make it easier for learners to describe what they see and practice speaking in context. What makes Emma stand out is her emphasis on relationship-building. She believes progress accelerates when learners feel safe, understood, and genuinely connected to their tutor—so she intentionally builds that ’friendship + learning’ dynamic over time. Best at helping: Learners who improve fastest with supportive conversation, steady encouragement, and a strong tutor–student relationship (especially younger or developing ESL learners).', '', '', 'Emma is on her school soccer team and loves singing—and she brings that same energy and confidence into speaking practice with students.', '', '', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('tutor-howard', 'person-howard', 'tutor', 'published', 160, '', '', false, false, 'Lead Tutor', '', '', '', '', '', 'English, Chinese (Mandarin)', '', '', 'Hearing Loss & Cochlear Implant Support, Pronunciation & Phoneme Coaching, Advanced & High-School Learners', '', '', 'Howard supports advanced learners and students with hearing loss by refining pronunciation and conversational fluency through structured, annotated instruction. He brings empathy, leadership, and clarity to every session.', '', '', 'Howard joined iHear after learning about its mission to support inclusive communication and recognizing the challenges faced by individuals with hearing loss. He is deeply motivated by empathy and believes that being truly ’heard’ requires patience, structure, and mutual understanding. As a tutor, Howard excels at helping students with intermediate to advanced English skills refine pronunciation and conversational fluency. He breaks complex ideas into clear steps, frequently annotates materials during sessions, and uses visual cues to support comprehension and note-taking. His sessions are especially effective for students who already have a foundation in English and want to sound more natural and confident in conversation. Howard also serves as Co-President of iHear, helping coordinate leadership initiatives and community outreach. He brings his tutoring mindset into leadership by emphasizing clarity, organization, and respect for individual voices. Even with leadership responsibilities, Howard remains actively engaged in tutoring to stay grounded in student experience.', '', '', 'Howard enjoys piano, music, karate, drawing, community service, and spending time with friends—activities that reflect both focus and creativity.', '', '', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('tutor-jayden-yang', 'person-jayden-yang', 'tutor', 'published', 170, 'Walt Whitman High School (Maryland)', '10', true, true, 'Team Lead', '', '', 'Walt Whitman High School (Maryland)', '', '', 'English, Chinese (Mandarin)', '', '', 'Structured & Step-by-Step Teaching, Personalized & Meticulous Coaching, Conversation & Real-World Speaking', '', '', 'Jayden keeps tutoring casual, clear, and stress-free—helping students understand the ’big picture’ by stripping away confusing jargon and explaining ideas in plain English. He loves using students'' interests to make learning click, and he also supports iHear behind the scenes through tech and team leadership.', '', '', 'Jayden joined iHear because he wants school to feel less stressful for students who are genuinely trying. He enjoys connecting with curious learners and showing them that topics that seem ’hard’ often become simple once someone explains them in the right way. As a tutor, Jayden keeps things super casual and honest—because he''s a student too. He doesn''t try to lecture like a teacher. Instead, he focuses on helping students figure out what they need, finish what they''re working on, and feel confident moving forward. He works best with learners who aren''t afraid to ask questions and stay engaged. Jayden also likes hearing about students'' interests and using them as real examples, so the material feels relevant and actually sticks. What makes Jayden unique is how he strips away confusing jargon and explains ideas in plain English, so students can understand the ’big picture’ without stress. He adapts how he explains things based on how each student learns—whether that means analogies, simpler wording, or a totally different angle until it clicks. Beyond tutoring, Jayden contributes to iHear''s operations as a Team Lead and community outreach speaker.', '', '', 'Jayden enjoys tech, problem-solving, and staying curious about how things work—skills he brings into making tutoring feel accessible and relatable.', '', '', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('tutor-jessie-chen', 'person-jessie-chen', 'tutor', 'published', 180, 'Dominican International School (Taipei)', '10', true, true, 'Lead Tutor', '', '', 'Dominican International School (Taipei)', '', '', 'English, Chinese (Mandarin)', '', '', 'ESL (English as Second Language Support), Confidence Building, Bilingual Support (English + Chinese)', '', '', 'Jessie supports learners with low confidence through patient, bilingual instruction. She adapts quickly between English and Chinese to help students feel understood and encouraged.', '', '', 'Jessie joined iHear after being invited by a friend and quickly connected with the program''s mission. She enjoys helping learners feel more confident in English, especially students who may be shy or unsure of their speaking skills. Jessie''s tutoring style is patient and passionate, with a preferred learner age range of 7–16. She supports students by explaining concepts clearly and encouraging them step-by-step. A key strength is her ability to switch smoothly between English and Chinese when needed—especially when a learner gets stuck on a difficult word or needs quick clarification to stay confident. Best at helping: Learners who need confidence support while developing everyday speaking skills, especially students who benefit from bilingual explanations (English + Chinese).', '', '', 'Jessie plays golf and guitar, and she enjoys activities that require steady practice—similar to how language learning improves through consistency.', '', '', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('tutor-karen-pan', 'person-karen-pan', 'tutor', 'published', 190, 'Montgomery Blair High School (Maryland)', '10', true, true, 'Lead Tutor', '', '', 'Montgomery Blair High School (Maryland)', '', '', 'English', '', '', 'Advanced & High-School Learners, Conversation & Real-World Speaking, Pronunciation & Phoneme Coaching', '', '', 'Karen supports middle and high school students through structured, conversation-based lessons. She emphasizes pronunciation, vocabulary, and reading comprehension.', '', '', 'Karen joined iHear to help students improve communication skills through patient, structured, conversation-based tutoring. She works best with middle to high school learners who already have an English foundation and enjoy learning through discussion and practical speaking. Her sessions emphasize conversation as a learning tool: students practice real speaking while also improving pronunciation and vocabulary. Karen also supports reading comprehension as part of communication development—helping students understand what they read and express ideas clearly. She balances structure with flexibility, adjusting to learner needs while keeping a clear learning path. Best at helping: Students with a foundation in English who want conversation-driven learning to improve pronunciation, vocabulary, and overall speaking clarity.', '', '', 'Karen plays piano and violin, and she enjoys drawing, making art, and listening to music—creative hobbies that align with her calm, steady teaching energy.', '', '', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('tutor-lisa-xu', 'person-lisa-xu', 'tutor', 'published', 200, 'Winston Churchill High School (Maryland)', '10', true, true, 'Team Lead', '', '', 'Winston Churchill High School (Maryland)', '', '', 'English, Chinese (Mandarin)', '', '', 'Beginner & Young Learners, Pronunciation & Phoneme Coaching, Confidence Building', '', '', 'Lisa creates fun, welcoming lessons for younger learners while also supporting operations and outreach to strengthen iHear as a community.', '', '', 'Lisa joined iHear because it''s a meaningful opportunity to support learners who are hearing-impaired while also growing her own skills through helping others. She prefers working with younger learners and focuses on making learning fun, comfortable, and confidence-building. Her tutoring style is patient, friendly, and encouraging. Lisa often uses visual examples and keeps the tone welcoming so learners feel happy, safe, and motivated to speak. Beyond tutoring, Lisa contributes to iHear''s operations as a Team Lead and community outreach speaker.', '', '', 'Sports, music, staying active, and trying new activities with friends.', '', '', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('tutor-marcus-ke', 'person-marcus-ke', 'tutor', 'published', 210, '', '', false, false, 'Lead Tutor', '', '', '', '', '', 'English, Chinese (Mandarin)', '', '', 'Pronunciation & Phoneme Coaching, Bilingual Support (English + Chinese), Personalized & Meticulous Coaching', '', '', 'Marcus supports learners—especially Mandarin speakers—by teaching English pronunciation carefully and making helpful comparisons to Mandarin sounds for clarity.', '', '', 'Marcus believes hearing differences should not become an obstacle to communication. His tutoring focuses on the intricacies of English pronunciation, especially areas that can be challenging for native Mandarin speakers. With a patient approach, Marcus highlights specific phonemes and patterns, often referencing similar or contrasting Mandarin sounds to help students understand what to change and how to practice. He also uses Mandarin explanations when needed so students can grasp concepts efficiently and feel confident applying them in speech.', '', '', 'Soccer, solving interesting math problems, playing guitar, and a fun juggling challenge record (600+ foot juggles with a tennis ball).', '', '', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('tutor-olivia-wang', 'person-olivia-wang', 'tutor', 'published', 220, 'Adams High School (Michigan)', '10', true, true, 'Lead Tutor', '', '', 'Adams High School (Michigan)', '', '', 'English, Chinese (Mandarin)', '', '', 'Hearing Loss & Cochlear Implant Support, Pronunciation & Phoneme Coaching, Personalized & Meticulous Coaching', '', '', 'Olivia supports learners through detailed explanations, visual modeling, and culturally relevant examples. She helps students connect language learning with real-world meaning.', '', '', 'Olivia joined iHear because she loves seeing student growth—and because iHear creates a unique space where both tutor and tutee learn something in every lesson. She''s motivated by progress that feels real, personal, and memorable. Her tutoring style is casual but thoughtful: she connects lessons to fun facts about English and American culture, while still using the session outline as checkpoints for skill-building. Olivia is especially patient and adapts her pacing to the learner—taking as long as needed and trying multiple explanations until the concept clicks. Olivia often teaches pronunciation and vocabulary using visual models. If ’just saying it’ isn''t enough, she may draw mouth shapes, sketch quick visuals, or model how sounds are formed. She focuses on explanations that fit the learner''s context so the student doesn''t just memorize—they understand. This creates stronger retention and helps learners connect language to real communication and culture. Best at helping: Learners who need patient guidance and detailed explanations—especially students working on pronunciation, confidence, and communication differences (including CI and ASD learners).', '', '', 'Olivia enjoys reading, drawing, and exploring creative hobbies that help her think visually—skills she brings into her tutoring sessions.', '', '', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('tutor-ria-kumar', 'person-ria-kumar', 'tutor', 'published', 230, 'Winston Churchill HS', '10', true, true, 'Lead Tutor', '', '', 'Winston Churchill HS', '', '', 'English, Hindi', '', '', 'Confidence Building · Conversational Practice · Supportive & Encouraging', '', '', 'Ria is a warm, encouraging tutor who helps learners gain confidence in English through natural conversation, vocabulary building, and steady practice.', '', '', 'Ria joined iHear because she believes communication is the bridge to connection—and she wants to help students feel confident using English in everyday life. In sessions, she creates a relaxed, supportive environment where learners can practice speaking without fear of mistakes. Ria focuses on building conversational fluency and vocabulary through real-world topics, and she adapts her approach to each student pace and interests. Her goal is to help students feel comfortable, capable, and proud of their progress.', '', '', 'Reading, cooking, listening to music, and exploring new languages.', '', '', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('tutor-tristan-echezarreta', 'person-tristan-echezarreta', 'tutor', 'published', 240, 'Walt Whitman High School (Maryland)', '10', true, true, 'Team Lead', '', '', 'Walt Whitman High School (Maryland)', '', '', 'English, Spanish', '', '', 'Conversation & Real-World Speaking, Confidence Building, Advanced & High-School Learners', '', '', 'Tristan helps students build confidence in speaking through supportive, interactive sessions. Inspired by his mother''s work with individuals with auditory disabilities, he brings empathy and encouragement into every lesson.', '', '', 'Tristan joined iHear to make a meaningful impact by helping learners strengthen communication skills and build confidence in inclusive learning environments. He was especially inspired by his mother''s experience tutoring individuals with auditory disabilities, and he brings that same empathy into every session. His tutoring style is patient, encouraging, and adaptive. Tristan enjoys working with older learners—especially high school and college students—who want to refine communication through practice that feels interactive and motivating. He focuses on creating a supportive atmosphere where learners feel comfortable taking risks, asking questions, and speaking more freely. Best at helping: Learners who want confidence-building, interactive speaking practice—especially those aiming for stronger real-world communication and smoother conversation.', '', '', 'Tristan enjoys reading and coding, and he''s always learning something new. Fun fact: he can recite the first 100 digits of π, which says a lot about his focus and memory!.', '', '', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('tutor-winston-wu', 'person-winston-wu', 'tutor', 'published', 250, 'Walt Whitman High School (Maryland)', '10', true, true, 'Lead Tutor', '', '', 'Walt Whitman High School (Maryland)', '', '', 'English, Chinese (Mandarin)', '', '', 'Structured & Step-by-Step Teaching, Pronunciation & Phoneme Coaching, Advanced & High-School Learners', '', '', 'Winston teaches with a patient, structured approach—breaking down complex ideas into clear steps so learners build strong foundations in communication.', '', '', 'Winston joined iHear after hearing great things from a friend and feeling inspired by the mission. He enjoys helping others and wanted to use his skills to support students in reaching their potential. His tutoring style is patient, adaptable, and focused on clear communication. Winston breaks down complex concepts into manageable pieces and supports learners with structured guidance that builds both understanding and confidence.', '', '', 'Table tennis, gaming, and helping others.', '', '', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com'),
  ('tutor-zoe-lu', 'person-zoe-lu', 'tutor', 'published', 260, 'Montgomery Blair High School (Maryland)', '10', true, true, 'Lead Tutor', '', '', 'Montgomery Blair High School (Maryland)', '', '', 'English, Chinese (Mandarin), Japanese', '', '', 'Hearing Loss & Cochlear Implant Support, ESL (English as Second Language Support), Confidence Building', '', '', 'Zoe founded iHear to make communication accessible for all learners. She teaches learners with hearing loss and ESL students through patient, individualized tutoring—while also leading tutor training and curriculum development across the program.', '', '', 'Zoe founded iHear because she believes communication should be accessible to everyone. Through tutoring learners with hearing loss and teaching ESL students, she saw how meaningful one-on-one, confidence-first support can be—especially when learning environments aren''t naturally inclusive. Her tutoring style is patient, supportive, and structured. She emphasizes clear communication, steady encouragement, and small adjustments that help students feel comfortable participating and expressing themselves. Zoe adapts each lesson to the learner''s needs and focuses on making real-life communication feel empowering. As Founder and Co-President, she provides executive leadership and represents iHear in community outreach and program growth. As Co-Director of Tutor Training & Curriculum, she helps design training frameworks, learning pathways, and quality standards so tutors can deliver consistent, inclusive instruction.', '', '', 'Clarinet, music, anime, K-pop (TXT), learning languages, and exploring different cultures.', '', '', 'ihearprogram@gmail.com', 'ihearprogram@gmail.com')
ON CONFLICT (id) DO NOTHING;
