"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { hasRiskyEnglish } from "../../../assets/text-language-guard";
import { useAdmin } from "../admin-context";
import { adminFetch, displayError } from "../admin-api";
import { LanguageGuardNotice } from "../language-guard";

type L10n={en:string;zhHant:string;zhHans:string};
type Milestone=Record<string,any>&{id:string;kind:"event"|"metrics";status:"draft"|"published";period:string;version:number;title:L10n;description:L10n;countryNames:L10n};
const l10n=():L10n=>({en:"",zhHant:"",zhHans:""});
const blank=()=>({kind:"metrics",period:new Date().toISOString().slice(0,7),volunteers:0,volunteersPlus:false,students:0,studentsPlus:false,sessions:0,sessionsPlus:false,countries:0,countryNames:l10n(),title:l10n(),description:l10n(),status:"draft",sortOrder:Number(new Date().toISOString().slice(0,7).replace("-",""))});
const copy={en:{title:"Impact data",intro:"Manage the homepage totals, as-of month, country list and journey events in three languages.",homepage:"Shown on the homepage",homepageHint:"The newest published impact-numbers record powers the 1,200+, 50+, 35+ and country cards on the homepage.",add:"Add record",search:"Search month or text",all:"All types",metrics:"Impact numbers",event:"Journey event",allStatus:"All statuses",draft:"Draft",published:"Published",edit:"Edit",trash:"Move to trash",empty:"No matching records.",newForm:"Add impact record",editForm:"Edit impact record",kind:"Record type",period:"Month / homepage as-of date",volunteers:"Active volunteers",students:"Students supported",sessions:"Tutoring sessions delivered",countries:"Countries served",plus:"Show + after number",countryNames:"Country names shown on homepage",eventTitle:"Event title",description:"Description",sort:"Display order",cancel:"Cancel",save:"Save draft",publish:"Save and publish",saving:"Saving…",conflict:"A newer record is available. Finish or cancel this draft to refresh."},zhHant:{title:"成果資料",intro:"集中管理首頁成果數字、截至月份、國家清單與三語歷程事件。",homepage:"顯示於首頁",homepageHint:"最新一筆已發布的成果數字會控制首頁的 1,200+、50+、35+ 與服務國家卡片。",add:"新增資料",search:"搜尋月份或文字",all:"全部類型",metrics:"成果數字",event:"歷程事件",allStatus:"全部狀態",draft:"草稿",published:"已發布",edit:"編輯",trash:"移至回收區",empty:"沒有符合條件的資料。",newForm:"新增成果資料",editForm:"編輯成果資料",kind:"資料類型",period:"月份／首頁截至日期",volunteers:"活躍志工",students:"受惠學生",sessions:"完成的輔導課程",countries:"服務國家數",plus:"數字後顯示 +",countryNames:"首頁顯示的國家名稱",eventTitle:"事件標題",description:"內容說明",sort:"顯示順序",cancel:"取消",save:"儲存草稿",publish:"儲存並發布",saving:"儲存中…",conflict:"已有較新的資料。請先完成或取消草稿再重新載入。"},zhHans:{title:"成果数据",intro:"集中管理首页成果数字、截至月份、国家清单与三语历程事件。",homepage:"显示于首页",homepageHint:"最新一笔已发布的成果数字会控制首页的 1,200+、50+、35+ 与服务国家卡片。",add:"新增数据",search:"搜索月份或文字",all:"全部类型",metrics:"成果数字",event:"历程事件",allStatus:"全部状态",draft:"草稿",published:"已发布",edit:"编辑",trash:"移至回收区",empty:"没有符合条件的数据。",newForm:"新增成果数据",editForm:"编辑成果数据",kind:"数据类型",period:"月份／首页截至日期",volunteers:"活跃志愿者",students:"受惠学生",sessions:"完成的辅导课程",countries:"服务国家数",plus:"数字后显示 +",countryNames:"首页显示的国家名称",eventTitle:"事件标题",description:"内容说明",sort:"显示顺序",cancel:"取消",save:"保存草稿",publish:"保存并发布",saving:"保存中…",conflict:"已有较新的数据。请先完成或取消草稿再重新加载。"}};
const translationCopy={en:{auto:"Automatically update Chinese translations",replace:"Also overwrite existing or manually edited Chinese",prepare:"Generate translation preview",preparing:"Translating…",ready:"Chinese preview ready. Review it, then save or publish."},zhHant:{auto:"自動更新中文翻譯",replace:"同時覆蓋既有或人工修改過的中文",prepare:"產生翻譯預覽",preparing:"翻譯中…",ready:"中文預覽已完成，請檢查後再儲存或發布。"},zhHans:{auto:"自动更新中文翻译",replace:"同时覆盖现有或人工修改过的中文",prepare:"生成翻译预览",preparing:"翻译中…",ready:"中文预览已完成，请检查后再保存或发布。"}};
export default function AdminImpactPage(){const{locale,setDirty,setSubmitting,submitting}=useAdmin();const text=copy[locale];const translateText=translationCopy[locale];const[items,setItems]=useState<Milestone[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[query,setQuery]=useState("");const[kind,setKind]=useState("all");const[status,setStatus]=useState("all");const[editing,setEditing]=useState<Milestone|null|"new">(null);const[form,setForm]=useState<any>(blank());const[tab,setTab]=useState<keyof L10n>("en");const[external,setExternal]=useState(false);const[autoTranslate,setAutoTranslate]=useState(true);const[replaceTranslations,setReplaceTranslations]=useState(false);const[translationReceipt,setTranslationReceipt]=useState("");const[translationReady,setTranslationReady]=useState(false);const[translating,setTranslating]=useState(false);const[englishGuardAccepted,setEnglishGuardAccepted]=useState(false);const original=useRef("");const autoOpen=useRef(false);const translationRequestActive=useRef(false);
 const load=async()=>{const d=await adminFetch<any>("/api/impact-milestones?includeDrafts=true");const next=d.milestones||[];setItems(next);setLoading(false);if(!autoOpen.current&&new URLSearchParams(window.location.search).get("edit")==="latest-metrics"){autoOpen.current=true;const latest=next.filter((item:Milestone)=>item.kind==="metrics"&&item.status==="published").sort((a:Milestone,b:Milestone)=>a.period.localeCompare(b.period)).at(-1);if(latest)open(latest)}};useEffect(()=>{load().catch(e=>{setError(displayError(e,locale));setLoading(false)})},[]);useEffect(()=>{const dirty=editing!==null&&(JSON.stringify(form)!==original.current||Boolean(translationReceipt));setDirty("impact-form",dirty);return()=>setDirty("impact-form",false)},[editing,form,translationReceipt,setDirty]);useEffect(()=>{const timer=setTimeout(()=>{(window as any).iHearLiveContent?.register("impact",{refresh:async()=>{if(editing){setExternal(true);return}await load()}})},200);return()=>clearTimeout(timer)},[editing]);
const filtered=useMemo(()=>{const q=query.toLowerCase().trim();return items.filter(x=>(kind==="all"||x.kind===kind)&&(status==="all"||x.status===status)&&(!q||[x.period,...Object.values(x.title||{}),...Object.values(x.description||{})].join(" ").toLowerCase().includes(q)))},[items,query,kind,status]);const latestPublishedMetricId=useMemo(()=>items.filter(x=>x.kind==="metrics"&&x.status==="published").sort((a,b)=>a.period.localeCompare(b.period)).at(-1)?.id,[items]);
 function englishSourceValues(source=form){return [source.title?.en,source.description?.en,source.countryNames?.en].map(value=>String(value||""))}
 function legacyRefreshFor(fields:Record<string,any>){let initial:any={};try{initial=JSON.parse(original.current||"{}")}catch{}const result:Record<string,Array<"zhHant"|"zhHans">>={};for(const field of Object.keys(fields)){if(String(fields[field]?.en||"").trim()===String(initial[field]?.en||"").trim())continue;const locales=(['zhHant','zhHans'] as Array<'zhHant'|'zhHans'>).filter(language=>String(fields[field]?.[language]||"").trim()===String(initial[field]?.[language]||"").trim());if(locales.length)result[field]=locales}return result}
 function open(item?:Milestone){const next=item?JSON.parse(JSON.stringify(item)):blank();setEditing(item||"new");setForm(next);setTab("en");setExternal(false);setAutoTranslate(true);setReplaceTranslations(false);setTranslationReceipt("");setTranslationReady(false);setEnglishGuardAccepted(false);setError("");original.current=JSON.stringify(next)}
function close(){if(submitting||translating)return;if(JSON.stringify(form)!==original.current||translationReceipt){if(window.confirm(locale==="en"?"Discard unsaved changes?":locale==="zhHans"?"放弃尚未保存的更改？":"放棄尚未儲存的變更？")){setEditing(null);setTranslationReceipt("");setTranslationReady(false)}}else setEditing(null)}
function loc(field:string,value:string){setForm((x:any)=>({...x,[field]:{...x[field],[tab]:value}}));if(tab==="en"){setTranslationReceipt("");setTranslationReady(false);setEnglishGuardAccepted(false)}}
 async function prepareTranslations(){if(submitting||translating||translationRequestActive.current||(hasRiskyEnglish(englishSourceValues())&&!englishGuardAccepted))return;const fields=Object.fromEntries(["title","description","countryNames"].filter(field=>Object.values(form[field]||{}).some(value=>String(value||"").trim())).map(field=>[field,form[field]]));if(!Object.values(fields).some((value:any)=>value.en?.trim())){setTranslationReady(true);return}const translatableFields=Object.fromEntries(Object.entries(fields).filter(([,value]:any)=>value.en?.trim()));translationRequestActive.current=true;setTranslating(true);setError("");try{const result=await adminFetch<any>("/api/admin/translations/preview",{method:"POST",body:JSON.stringify({resource:{type:"impact",scope:"",id:editing==="new"?"__new__":(editing as Milestone).id,version:editing==="new"?undefined:(editing as Milestone).version},fields:translatableFields,allowCjkEnglish:englishGuardAccepted,force:replaceTranslations?Object.fromEntries(Object.keys(translatableFields).map(field=>[field,["zhHant","zhHans"]])):{},refreshLegacy:legacyRefreshFor(translatableFields)})});setForm((current:any)=>({...current,...Object.fromEntries(Object.entries(result.fields).map(([field,value]:any)=>[field,value.value]))}));setTranslationReceipt(result.receipt);setTranslationReady(true)}catch(e){setError(displayError(e,locale))}finally{translationRequestActive.current=false;setTranslating(false)}}
async function save(publish:boolean){if(submitting||translating)return;if(autoTranslate&&!translationReady){await prepareTranslations();return}setSubmitting(true);setError("");try{const body={...form,status:publish?"published":"draft",volunteers:Number(form.volunteers),students:Number(form.students),sessions:Number(form.sessions),countries:Number(form.countries),sortOrder:Number(form.sortOrder),translationReceipt:autoTranslate&&translationReceipt?translationReceipt:undefined,...(editing!=="new"?{version:(editing as Milestone).version}:{})};const d=editing==="new"?await adminFetch<any>("/api/impact-milestones",{method:"POST",body:JSON.stringify(body)}):await adminFetch<any>(`/api/impact-milestones/${(editing as Milestone).id}`,{method:"PATCH",body:JSON.stringify(body)});setItems(x=>x.some(v=>v.id===d.milestone.id)?x.map(v=>v.id===d.milestone.id?d.milestone:v):[...x,d.milestone]);original.current=JSON.stringify(d.milestone);setEditing(null);setTranslationReceipt("");setTranslationReady(false);(window as any).iHearLiveContent?.announce("impact",d.revision)}catch(e){setError(displayError(e,locale))}finally{setSubmitting(false)}}
async function trash(item:Milestone){if(submitting)return;setSubmitting(true);try{const d=await adminFetch<any>(`/api/impact-milestones/${item.id}`,{method:"DELETE",body:JSON.stringify({version:item.version})});setItems(x=>x.filter(v=>v.id!==item.id));(window as any).iHearLiveContent?.announce("impact",d.revision)}catch(e){setError(displayError(e,locale))}finally{setSubmitting(false)}}
return <section className="admin-page"><header className="admin-page-head"><div><h1>{text.title}</h1><p>{text.intro}</p></div><button className="admin-button primary" onClick={()=>open()}>{text.add}</button></header><p className="admin-alert admin-success">{text.homepageHint}</p>{error&&<p className="admin-alert" role="alert">{error}</p>}<div className="admin-toolbar"><input className="admin-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder={text.search}/><select className="admin-select" value={kind} onChange={e=>setKind(e.target.value)}><option value="all">{text.all}</option><option value="metrics">{text.metrics}</option><option value="event">{text.event}</option></select><select className="admin-select" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">{text.allStatus}</option><option value="draft">{text.draft}</option><option value="published">{text.published}</option></select></div>{loading?<p>Loading…</p>:filtered.length?<div className="admin-card-grid">{filtered.sort((a,b)=>a.sortOrder-b.sortOrder).map(item=><article className="admin-card" key={item.id}><div className="admin-card-head"><div><h2>{item.kind==="metrics"?`${item.period} · ${text.metrics}`:(item.title?.[locale]||item.title?.en||item.period)}</h2><p>{item.description?.[locale]||item.description?.en||"—"}</p></div><div>{item.id===latestPublishedMetricId&&<span className="admin-status published">{text.homepage}</span>}<span className={`admin-status ${item.status}`}>{item.status==="published"?text.published:text.draft}</span></div></div>{item.kind==="metrics"&&<p>{text.students}: {item.students}{item.studentsPlus?"+":""} · {text.sessions}: {item.sessions}{item.sessionsPlus?"+":""}</p>}<div className="admin-card-actions"><button className="admin-button secondary" onClick={()=>open(item)}>{text.edit}</button><button className="admin-button danger" onClick={()=>trash(item)}>{text.trash}</button></div></article>)}</div>:<div className="admin-empty">{text.empty}</div>}
{editing&&<><button className="admin-drawer-backdrop" aria-label={text.cancel} onClick={close}/><aside className="admin-drawer" role="dialog" aria-modal="true" aria-labelledby="impact-form-title" aria-busy={submitting||translating}>
 <div className="admin-drawer-head"><h2 id="impact-form-title">{editing==="new"?text.newForm:text.editForm}</h2><button className="admin-icon-button" disabled={submitting||translating} onClick={close}>×</button></div>{external&&<p className="admin-alert">{text.conflict}</p>}
 <div className="admin-form"><div className="admin-form-grid"><label className="admin-field"><span>{text.kind}</span><select disabled={submitting||translating} value={form.kind} onChange={e=>{setForm((x:any)=>({...x,kind:e.target.value}));setTranslationReceipt("");setTranslationReady(false)}}><option value="metrics">{text.metrics}</option><option value="event">{text.event}</option></select></label><label className="admin-field"><span>{text.period}</span><input disabled={submitting||translating} type="month" value={form.period} onChange={e=>setForm((x:any)=>({...x,period:e.target.value}))}/></label><label className="admin-field"><span>{text.sort}</span><input disabled={submitting||translating} type="number" min="0" value={form.sortOrder} onChange={e=>setForm((x:any)=>({...x,sortOrder:e.target.value}))}/></label></div>
 {form.kind==="metrics"&&<div className="admin-form-grid">{["volunteers","students","sessions"].map(field=><div key={field}><label className="admin-field"><span>{(text as any)[field]}</span><input disabled={submitting||translating} type="number" min="0" value={form[field]} onChange={e=>setForm((x:any)=>({...x,[field]:e.target.value}))}/></label><label className="admin-checkbox"><input disabled={submitting||translating} type="checkbox" checked={form[`${field}Plus`]} onChange={e=>setForm((x:any)=>({...x,[`${field}Plus`]:e.target.checked}))}/>{text.plus}</label></div>)}<label className="admin-field"><span>{text.countries}</span><input disabled={submitting||translating} type="number" min="0" max="250" value={form.countries} onChange={e=>setForm((x:any)=>({...x,countries:e.target.value}))}/></label></div>}
  <div className="admin-translation-controls"><label className="admin-checkbox"><input type="checkbox" checked={autoTranslate} disabled={submitting||translating} onChange={e=>{setAutoTranslate(e.target.checked);setTranslationReceipt("");setTranslationReady(false)}}/>{translateText.auto}</label>{autoTranslate&&<label className="admin-checkbox"><input type="checkbox" checked={replaceTranslations} disabled={submitting||translating} onChange={e=>{setReplaceTranslations(e.target.checked);setTranslationReceipt("");setTranslationReady(false)}}/>{translateText.replace}</label>}{translationReady&&<p className="admin-translation-status" role="status">{translateText.ready}</p>}</div>
 <div className="admin-locale-tabs">{(["en","zhHant","zhHans"] as (keyof L10n)[]).map(x=><button type="button" className={tab===x?"active":""} key={x} onClick={()=>setTab(x)}>{x==="en"?"English":x==="zhHant"?"繁體中文":"简体中文"}</button>)}</div>
  {form.kind==="event"&&<><label className="admin-field"><span>{text.eventTitle}</span><input disabled={submitting||translating} value={form.title?.[tab]||""} onChange={e=>loc("title",e.target.value)}/></label><LanguageGuardNotice locale={locale} language={tab} value={form.title?.[tab]||""} disabled={submitting||translating} englishAccepted={englishGuardAccepted} onAcceptEnglish={()=>setEnglishGuardAccepted(true)} onChange={value=>loc("title",value)}/></>}{form.kind==="metrics"&&<><label className="admin-field"><span>{text.countryNames}</span><input disabled={submitting||translating} value={form.countryNames?.[tab]||""} onChange={e=>loc("countryNames",e.target.value)}/></label><LanguageGuardNotice locale={locale} language={tab} value={form.countryNames?.[tab]||""} disabled={submitting||translating} englishAccepted={englishGuardAccepted} onAcceptEnglish={()=>setEnglishGuardAccepted(true)} onChange={value=>loc("countryNames",value)}/></>}<label className="admin-field"><span>{text.description}</span><textarea disabled={submitting||translating} value={form.description?.[tab]||""} onChange={e=>loc("description",e.target.value)}/></label><LanguageGuardNotice locale={locale} language={tab} value={form.description?.[tab]||""} disabled={submitting||translating} englishAccepted={englishGuardAccepted} onAcceptEnglish={()=>setEnglishGuardAccepted(true)} onChange={value=>loc("description",value)}/>
 <div className="admin-form-footer"><button className="admin-button secondary" disabled={submitting||translating} onClick={close}>{text.cancel}</button><button className="admin-button secondary" disabled={submitting||translating||external} onClick={()=>save(false)}>{translating?translateText.preparing:submitting?text.saving:autoTranslate&&!translationReady?translateText.prepare:text.save}</button><button className="admin-button primary" disabled={submitting||translating||external} onClick={()=>save(true)}>{translating?translateText.preparing:submitting?text.saving:autoTranslate&&!translationReady?translateText.prepare:text.publish}</button></div></div></aside></>}
</section>}
