"use client";

import { useEffect, useState } from "react";
import { useAdmin } from "../admin-context";
import { adminFetch, displayError } from "../admin-api";

const copy={en:{title:"Trash",intro:"Restore records at any time. Resource links are retained; only owners can permanently delete team or impact records.",team:"Team",impact:"Impact",resource:"Resources",restore:"Restore",permanent:"Delete permanently",empty:"Trash is empty.",confirm:"This cannot be undone. Permanently delete this record?"},zhHant:{title:"回收區",intro:"資料可隨時復原。資源連結會保留；團隊與成果資料只有擁有者能永久刪除。",team:"團隊名冊",impact:"成果資料",resource:"資源連結",restore:"復原",permanent:"永久刪除",empty:"回收區目前沒有資料。",confirm:"永久刪除後無法復原。確定要刪除這筆資料嗎？"},zhHans:{title:"回收区",intro:"数据可随时恢复。资源链接会保留；团队与成果数据只有拥有者能永久删除。",team:"团队名册",impact:"成果数据",resource:"资源链接",restore:"恢复",permanent:"永久删除",empty:"回收区目前没有数据。",confirm:"永久删除后无法恢复。确定要删除这笔数据吗？"}};
export default function TrashPage(){const{locale,principal,submitting,setSubmitting}=useAdmin();const text=copy[locale];const[team,setTeam]=useState<any[]>([]);const[impact,setImpact]=useState<any[]>([]);const[resources,setResources]=useState<any[]>([]);const[error,setError]=useState("");const[loading,setLoading]=useState(true);async function load(){const[t,i,r]=await Promise.all([adminFetch<any>("/api/team-profiles?includeDeleted=true"),adminFetch<any>("/api/impact-milestones?includeArchived=true"),adminFetch<any>("/api/resources?includeArchived=true")]);setTeam([...(t.leaders||[]),...(t.tutors||[])]);setImpact(i.milestones||[]);setResources(r.items||[]);setLoading(false)}useEffect(()=>{load().catch(e=>{setError(displayError(e,locale));setLoading(false)})},[]);
async function restore(kind:"team"|"impact"|"resource",item:any){setSubmitting(true);setError("");try{if(kind==="team")await adminFetch(`/api/team-profiles/${item.id}/restore`,{method:"POST",body:JSON.stringify({profileVersion:item.profileVersion})});else await adminFetch(`/api/${kind==="resource"?"resources":"impact-milestones"}/${item.id}/restore`,{method:"POST",body:JSON.stringify({version:item.version})});if(kind==="team")setTeam(x=>x.filter(v=>v.id!==item.id));else if(kind==="resource")setResources(x=>x.filter(v=>v.id!==item.id));else setImpact(x=>x.filter(v=>v.id!==item.id))}catch(e){setError(displayError(e,locale))}finally{setSubmitting(false)}}
async function permanent(kind:"team"|"impact",item:any){if(!confirm(text.confirm))return;setSubmitting(true);try{await adminFetch(kind==="team"?`/api/team-profiles/${item.id}`:`/api/impact-milestones/${item.id}`,{method:"DELETE",body:JSON.stringify(kind==="team"?{profileVersion:item.profileVersion,permanent:true}:{version:item.version,permanent:true})});if(kind==="team")setTeam(x=>x.filter(v=>v.id!==item.id));else setImpact(x=>x.filter(v=>v.id!==item.id))}catch(e){setError(displayError(e,locale))}finally{setSubmitting(false)}}
const card=(kind:"team"|"impact"|"resource",item:any)=><article className="admin-card" key={item.id}><div className="admin-card-head"><div><h3>{kind==="team"?item.name:(item.title?.[locale]||item.title?.en||item.period)}</h3><p>{kind==="team"?item.role?.[locale]||item.section:item.description?.[locale]||item.kind}</p></div><span className="admin-status trash">Trash</span></div><div className="admin-card-actions"><button className="admin-button secondary" disabled={submitting} onClick={()=>restore(kind,item)}>{text.restore}</button>{principal.role==="owner"&&kind!=="resource"&&<button className="admin-button danger" disabled={submitting} onClick={()=>permanent(kind,item)}>{text.permanent}</button>}</div></article>;
return <section className="admin-page"><header className="admin-page-head"><div><h1>{text.title}</h1><p>{text.intro}</p></div></header>{error&&<p className="admin-alert" role="alert">{error}</p>}{loading?<p>Loading…</p>:team.length||impact.length||resources.length?<><h2>{text.team}</h2><div className="admin-card-grid">{team.map(x=>card("team",x))}</div><h2>{text.impact}</h2><div className="admin-card-grid">{impact.map(x=>card("impact",x))}</div><h2>{text.resource}</h2><div className="admin-card-grid">{resources.map(x=>card("resource",x))}</div></>:<div className="admin-empty">{text.empty}</div>}</section>}
