[build]
  publish = "."

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/programs"
  to = "/programs.html"
  status = 200

[[redirects]]
  from = "/impact"
  to = "/impact.html"
  status = 200

[[redirects]]
  from = "/team"
  to = "/team.html"
  status = 200

[[redirects]]
  from = "/submit-bio"
  to = "/submit-bio.html"
  status = 200

[[redirects]]
  from = "/stories"
  to = "/stories.html"
  status = 200

[[redirects]]
  from = "/get-involved"
  to = "/get-involved.html"
  status = 200

[[redirects]]
  from = "/academy"
  to = "/academy.html"
  status = 200

[[redirects]]
  from = "/donate"
  to = "/donate.html"
  status = 200

[[redirects]]
  from = "/resources"
  to = "/resources.html"
  status = 200

[[redirects]]
  from = "/faq"
  to = "/faq.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200
