"use client";

import { useEffect, useState } from "react";
import { useAdmin } from "../admin-context";
import { adminFetch, displayError } from "../admin-api";

const copy={en:{title:"Administrators",intro:"Fixed owners come from environment settings. Add or disable editors here.",owners:"Fixed owners",editors:"Editors",add:"Add editor",email:"Google account email",enabled:"Enabled",disabled:"Disabled",disable:"Disable",enable:"Enable",adding:"Adding…",empty:"No editors have been added."},zhHant:{title:"管理員",intro:"固定擁有者來自環境設定；您可以在此新增或停用編輯者。",owners:"固定擁有者",editors:"編輯者",add:"新增編輯者",email:"Google 帳號 Email",enabled:"已啟用",disabled:"已停用",disable:"停用",enable:"啟用",adding:"新增中…",empty:"尚未新增編輯者。"},zhHans:{title:"管理员",intro:"固定拥有者来自环境设置；您可以在此新增或停用编辑者。",owners:"固定拥有者",editors:"编辑者",add:"新增编辑者",email:"Google 账号 Email",enabled:"已启用",disabled:"已停用",disable:"停用",enable:"启用",adding:"新增中…",empty:"尚未新增编辑者。"}};
export default function AdminAccountsPage(){const{locale,principal,setDirty,setSubmitting}=useAdmin();const text=copy[locale];const[owners,setOwners]=useState<string[]>([]);const[editors,setEditors]=useState<any[]>([]);const[email,setEmail]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState("");
useEffect(()=>{adminFetch<any>("/api/admin/accounts").then(d=>{setOwners(d.owners||[]);setEditors(d.editors||[])}).catch(e=>setError(displayError(e,locale)))},[locale]);
useEffect(()=>{setDirty("admin-account-form",Boolean(email.trim()));return()=>setDirty("admin-account-form",false)},[email,setDirty]);
if(principal.role!=="owner")return <section className="admin-page"><p className="admin-alert">Owner access is required.</p></section>;
async function add(){if(busy||!email.trim())return;setBusy(true);setSubmitting(true);setError("");try{const d=await adminFetch<any>("/api/admin/accounts",{method:"POST",body:JSON.stringify({email})});setEditors(x=>[...x,d.account].sort((a,b)=>a.email.localeCompare(b.email)));setEmail("")}catch(e){setError(displayError(e,locale))}finally{setBusy(false);setSubmitting(false)}}
async function toggle(item:any){if(busy)return;setBusy(true);setSubmitting(true);try{const d=await adminFetch<any>(`/api/admin/accounts/${encodeURIComponent(item.email)}`,{method:"PATCH",body:JSON.stringify({enabled:!item.enabled,version:item.version})});setEditors(x=>x.map(v=>v.email===item.email?d.account:v))}catch(e){setError(displayError(e,locale))}finally{setBusy(false);setSubmitting(false)}}
return <section className="admin-page"><header className="admin-page-head"><div><h1>{text.title}</h1><p>{text.intro}</p></div></header>{error&&<p className="admin-alert" role="alert">{error}</p>}<div className="admin-panel"><h2>{text.owners}</h2><div className="admin-card-grid">{owners.map(owner=><div className="admin-card" key={owner}><strong>{owner}</strong><p><span className="admin-status published">Owner</span></p></div>)}</div></div><div className="admin-panel" style={{marginTop:18}}><h2>{text.editors}</h2><div className="admin-toolbar"><input className="admin-search" value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder={text.email}/><button className="admin-button primary" disabled={busy||!email.trim()} onClick={add}>{busy?text.adding:text.add}</button></div>{editors.length?<div className="admin-table-wrap"><table className="admin-table"><tbody>{editors.map(item=><tr key={item.email}><td><strong>{item.email}</strong></td><td><span className={`admin-status ${item.enabled?"published":"archived"}`}>{item.enabled?text.enabled:text.disabled}</span></td><td><button className="admin-button secondary" disabled={busy} onClick={()=>toggle(item)}>{item.enabled?text.disable:text.enable}</button></td></tr>)}</tbody></table></div>:<p className="admin-muted">{text.empty}</p>}</div></section>}
