export const copy = {
  en: { category: "Category", form: "Forms / useful links", article: "Articles", heading: "Resources", intro: "Manage forms and external articles. Names here do not change the original content.", add: "Add resource", title: "Name", description: "Description (optional)", url: "HTTPS link", order: "Display order", edit: "Edit", hide: "Hide", publish: "Publish", trash: "Move to trash", confirm: "Remove this website link? The original content will remain available.", empty: "No resources yet.", retry: "Reload saved resources", draft: "Draft", published: "Published", cancel: "Cancel", save: "Save draft", savePublish: "Save and publish", auto: "Automatically update Chinese translations", force: "Also replace manually edited Chinese", preview: "Generate translation preview", ready: "Preview ready. Review the text, then save.", pending: "Working…", view: "View Resources", nameRequired: "Enter an English name.", conflict: "This resource changed elsewhere. Your draft is kept; close it and reload before saving." },
  zhHant: { category: "分類", form: "表單／常用連結", article: "文章", heading: "資源管理", intro: "管理資源頁上的表單與外部文章。在此改名不會修改原始內容。", add: "新增資源", title: "名稱", description: "用途說明（選填）", url: "HTTPS 連結", order: "顯示順序", edit: "編輯", hide: "隱藏", publish: "發布", trash: "移至回收區", confirm: "移除此網站連結？來源內容仍會保留。", empty: "目前沒有資源。", retry: "重新讀取已儲存資料", draft: "草稿", published: "已發布", cancel: "取消", save: "儲存草稿", savePublish: "儲存並發布", auto: "自動更新中文翻譯", force: "同時覆蓋人工修改的中文", preview: "產生翻譯預覽", ready: "預覽已完成，請檢查文字後再儲存。", pending: "處理中…", view: "查看資源頁", nameRequired: "請填寫英文名稱。", conflict: "此資料已被其他管理員更新。您的草稿已保留，請關閉並重新讀取後再儲存。" },
  zhHans: { category: "分类", form: "表单／常用链接", article: "文章", heading: "资源管理", intro: "管理资源页上的表单与外部文章。在此改名不会修改原始内容。", add: "新增资源", title: "名称", description: "用途说明（选填）", url: "HTTPS 链接", order: "显示顺序", edit: "编辑", hide: "隐藏", publish: "发布", trash: "移至回收区", confirm: "移除此网站链接？来源内容仍会保留。", empty: "目前没有资源。", retry: "重新读取已保存数据", draft: "草稿", published: "已发布", cancel: "取消", save: "保存草稿", savePublish: "保存并发布", auto: "自动更新中文翻译", force: "同时覆盖人工修改的中文", preview: "生成翻译预览", ready: "预览已完成，请检查文字后再保存。", pending: "处理中…", view: "查看资源页", nameRequired: "请填写英文名称。", conflict: "此数据已被其他管理员更新。您的草稿已保留，请关闭并重新读取后再保存。" },
};
export const workflowCopy = {
  en: { next: "Next: preview translations", step: "Step 1: preview translations. Step 2: confirm saving or publishing. Nothing is saved yet.", confirmDraft: "Confirm save draft", confirmPublish: "Confirm publish", keepPublished: "Save changes (keep published)", unpublish: "Save as draft and unpublish", confirmUnpublish: "This resource will be removed from the public list and saved as a draft. Continue?", previewAgain: "The translation preview is no longer valid. Your input is kept. Generate a new preview to continue.", urlError: "Enter a complete HTTPS link without a username or password.", translationError: "Could not generate the translation preview. Your input is kept. Try again or enter Chinese manually.", saveError: "Could not save. Your input is kept. Please try again." },
  zhHant: { next: "下一步：預覽翻譯", step: "第 1 步：預覽翻譯；第 2 步：確認儲存或發布。目前尚未儲存。", confirmDraft: "確認儲存草稿", confirmPublish: "確認發布", keepPublished: "儲存變更（維持發布）", unpublish: "改為草稿並下架", confirmUnpublish: "這筆資源將從公開清單下架，並保留為草稿。確定繼續？", previewAgain: "翻譯預覽已過期或失效，輸入內容已保留。請重新產生預覽後再儲存。", urlError: "請輸入完整的 HTTPS 網址，且網址不可包含帳號或密碼。", translationError: "無法產生翻譯預覽，輸入內容已保留。請重試，或手動填寫中文後再預覽。", saveError: "儲存失敗，輸入內容已保留，請再試一次。" },
  zhHans: { next: "下一步：预览翻译", step: "第 1 步：预览翻译；第 2 步：确认保存或发布。目前尚未保存。", confirmDraft: "确认保存草稿", confirmPublish: "确认发布", keepPublished: "保存更改（保持发布）", unpublish: "改为草稿并下架", confirmUnpublish: "这条资源将从公开列表下架，并保留为草稿。确定继续？", previewAgain: "翻译预览已过期或失效，输入内容已保留。请重新生成预览后再保存。", urlError: "请输入完整的 HTTPS 网址，且网址不可包含账号或密码。", translationError: "无法生成翻译预览，输入内容已保留。请重试，或手动填写中文后再预览。", saveError: "保存失败，输入内容已保留，请再试一次。" },
};
export const languageLabels = { en: "English", zhHant: "繁體中文", zhHans: "简体中文" };
