export const topicCopy = {
  en: {
    intro: "Manage topics and their resources. Changing a website entry does not change the original form or document.",
    topics: "Topics", items: "Resources", addTopic: "Add topic", addItem: "Add resource", editTopic: "Edit topic", editItem: "Edit resource",
    topic: "Topic", type: "Resource type", external_link: "External link", email_request: "Email request", text: "Text only",
    all: "All active", allTopics: "All topics", filter: "Status", draft: "Draft / hidden", published: "Published", archived: "Trash", restore: "Restore",
    loading: "Loading topics and resources…", empty: "No records match this filter.", count: "Referenced resources (including trash)",
    hiddenParent: "The topic is hidden. Publishing this resource alone will not make it public.",
    typeHelp: "Email requests and text entries do not need a link. For text entries, put the content in the description.",
    archive: "Move this record to trash? Its content is kept and can be restored.",
    topicHide: "Hide this topic and all its resources from visitors? The resources keep their own status.",
    notEmpty: "This topic still contains resources, including items in trash. Move its active resources to another topic; restore and move any trashed resources first. To temporarily take the whole topic offline, use Hide instead.",
    topicUnavailable: "This topic is no longer available. Reload the saved data and select an active topic.",
    archivedRecord: "This record is in trash. Reload the list and restore it before editing.",
    missing: "This record is no longer available. Reload the saved data.",
    failed: "Could not load the saved data. Please try Reload saved resources.",
    mutationFailed: "Could not save this change. Nothing has been marked successful. Reload the saved data to check its status before retrying.",
    invalid: "Check the English name, resource type, topic, link and whole-number display order, then try again.",
    schema: "Resources management is not ready on this environment. Please contact the website administrator.",
    latest: "Load latest record", discard: "Replace your unsaved input with the latest saved record? Copy any text you wish to keep before continuing.",
    loaded: "Latest saved record loaded. Review it before making new changes.", saved: "Saved successfully.", restored: "Restored to its previous status.",
    hidden: "Hidden from visitors. The content is kept.", archivedDone: "Moved to trash. The content is kept.",
    conflict: "Another administrator changed this record. Your input is kept. Load the latest record before saving again.",
    listConflict: "Another administrator changed this record. Reload saved resources before trying again.",
    chooseTopic: "Select a topic", viewItems: "View resources", activeTopicRequired: "Create or restore a topic before adding resources.",
  },
  zhHant: {
    intro: "管理主題與主題下的資源。在此修改網站入口，不會更動原始表單或文件。",
    topics: "主題管理", items: "項目管理", addTopic: "新增主題", addItem: "新增資源", editTopic: "編輯主題", editItem: "編輯資源",
    topic: "所屬主題", type: "項目種類", external_link: "外部連結", email_request: "Email 索取", text: "純文字",
    all: "全部（不含回收區）", allTopics: "全部主題", filter: "狀態篩選", draft: "草稿／隱藏", published: "已發布", archived: "回收區", restore: "復原",
    loading: "正在載入主題與資源…", empty: "目前篩選條件下沒有資料。", count: "引用項目數（含回收區）",
    hiddenParent: "此主題目前隱藏中。單獨發布項目，訪客仍看不到。",
    typeHelp: "Email 索取與純文字不需填連結；純文字內容請填寫在用途說明。",
    archive: "將這筆資料移至回收區？內容會保留，之後可以復原。",
    topicHide: "隱藏整個主題及其資源？各項目的原本狀態會保留。",
    notEmpty: "此主題仍有項目引用，包含回收區項目。請先將項目移至其他主題；回收區項目需先復原再移動。若只是暫時下架整個主題，請使用「隱藏」。",
    topicUnavailable: "此主題已無法使用。請重新讀取已儲存資料，再選擇可用的主題。",
    archivedRecord: "這筆資料已在回收區。請重新讀取清單，復原後再編輯。",
    missing: "找不到這筆資料，請重新讀取已儲存資料。",
    failed: "無法載入已儲存資料，請按「重新讀取已儲存資料」重試。",
    mutationFailed: "此次操作未能確認成功。請重新讀取已儲存資料，確認狀態後再試一次。",
    invalid: "請檢查英文名稱、項目種類、主題、連結與整數顯示順序後重試。",
    schema: "此環境的資源管理尚未準備完成，請聯絡網站管理員。",
    latest: "取得此筆最新資料", discard: "要用最新已儲存資料取代目前尚未儲存的輸入嗎？請先複製您想保留的文字。",
    loaded: "已取得最新資料，請核對後再修改。", saved: "已儲存成功。", restored: "已復原至回收前的狀態。",
    hidden: "已隱藏，訪客已看不到；內容仍保留。", archivedDone: "已移至回收區，內容仍保留。",
    conflict: "此資料已被其他管理員更新。您的輸入已保留，請先取得此筆最新資料，再重新儲存。",
    listConflict: "此資料已被其他管理員更新，請重新讀取已儲存資料後再操作。",
    chooseTopic: "請選擇主題", viewItems: "查看項目", activeTopicRequired: "請先新增或復原一個主題，再新增資源。",
  },
  zhHans: {
    intro: "管理主题与主题下的资源。在此修改网站入口，不会更改原始表单或文档。",
    topics: "主题管理", items: "项目管理", addTopic: "新增主题", addItem: "新增资源", editTopic: "编辑主题", editItem: "编辑资源",
    topic: "所属主题", type: "项目种类", external_link: "外部链接", email_request: "Email 索取", text: "纯文字",
    all: "全部（不含回收区）", allTopics: "全部主题", filter: "状态筛选", draft: "草稿／隐藏", published: "已发布", archived: "回收区", restore: "复原",
    loading: "正在加载主题与资源…", empty: "当前筛选条件下没有数据。", count: "引用项目数（含回收区）",
    hiddenParent: "此主题当前隐藏中。单独发布项目，访客仍看不到。",
    typeHelp: "Email 索取与纯文字不需填写链接；纯文字内容请填写在用途说明。",
    archive: "将这条数据移至回收区？内容会保留，之后可以复原。",
    topicHide: "隐藏整个主题及其资源？各项目的原本状态会保留。",
    notEmpty: "此主题仍有项目引用，包括回收区项目。请先将项目移至其他主题；回收区项目需先复原再移动。如只需暂时下架整个主题，请使用“隐藏”。",
    topicUnavailable: "此主题已无法使用。请重新读取已保存数据，再选择可用的主题。",
    archivedRecord: "这条数据已在回收区。请重新读取列表，复原后再编辑。",
    missing: "找不到这条数据，请重新读取已保存数据。",
    failed: "无法加载已保存数据，请按“重新读取已保存数据”重试。",
    mutationFailed: "此次操作未能确认成功。请重新读取已保存数据，确认状态后再试一次。",
    invalid: "请检查英文名称、项目种类、主题、链接与整数显示顺序后重试。",
    schema: "此环境的资源管理尚未准备完成，请联系网站管理员。",
    latest: "获取此条最新数据", discard: "要用最新已保存数据替换当前尚未保存的输入吗？请先复制您想保留的文字。",
    loaded: "已获取最新数据，请核对后再修改。", saved: "已保存成功。", restored: "已复原至回收前的状态。",
    hidden: "已隐藏，访客已看不到；内容仍保留。", archivedDone: "已移至回收区，内容仍保留。",
    conflict: "此数据已被其他管理员更新。您的输入已保留，请先获取此条最新数据，再重新保存。",
    listConflict: "此数据已被其他管理员更新，请重新读取已保存数据后再操作。",
    chooseTopic: "请选择主题", viewItems: "查看项目", activeTopicRequired: "请先新增或复原一个主题，再新增资源。",
  },
};
